version: '3.9'
services:
  db:
    image: mysql:8.0.29
    container_name: organization_mysql
    restart: always
    ports:
      - "3306:3306"
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: organization
      MYSQL_ROOT_PASSWORD: rkskekfk1234
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  organization:
    build:
      context: .
    container_name: organization
    ports:
      - "9000:9000"
    restart: always
    environment:
      MYSQL_URL: jdbc:mysql://db/organization
    depends_on:
      db:
        condition: service_healthy
